name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloudinary_public: ^0.11.0
  dio: ^4.0.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

